include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    avoid_catching_errors: false
    one_member_abstracts: false
    avoid_returning_this: false
    prefer_constructors_over_static_methods: false